[env]
RIT_USERNAME="goal"
RIT_PASSWORD="credit"
RIT_PRINT_DETAIL="summary"
RIT_LOOP_SLEEP="0.5"
RIT_ARB_INTENT_DEADLINE_TICKS="7"
RIT_MAX_UNHEDGED_TICKS="15"
RIT_EXECUTION_POLICY="market"
RIT_PASSIVE_WAIT_TICKS="1"
